spring:
    datasource:
        url: jdbc:mysql://localhost:3306/SpringBootDB?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Pramodtf@1998     
    jpa:
        hibernate:
            ddl-auto: update 
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER   
   
logging:
    level:
        com:
            thoughtfocus: DEBUG
            
    pattern:
        console: (%d %m %n)
   
     
